input {
  tcp {
    port => 5044
    codec => json
  }
  beats {
    port => 5045
  }
}

filter {
  if [logger_name] =~ "auth" {
    mutate { add_field => { "service" => "auth-service" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ecommerce-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
