apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  RATE_LIMIT_PER_MINUTE: "120"
  GATEWAY_REQUEST_TIMEOUT: "5"
