apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ecommerce
  labels:
    app: cart-service
spec:
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: http
  selector:
    app: cart-service
  type: ClusterIP
